# Generated by Django 3.0.8 on 2020-07-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200621_2249'),
        ('blog', '0003_auto_20200630_1435'),
    ]

    operations = [
    ]
